export const WorkData = [
    {
        id: 1,
        title: "Peep × Triptii Dimri",
        slug: "peep-triptii-dimri",
        description: "Capital and celebrity, timed to give the round visible runway and fund the campaign that followed.",
        engagement: "Fundraise + Brand Ambassador",
        category: "Beauty",
        scope: "12 months • Active",
        services: [
            "Capital",
            "Talent",
            "Strategy"
        ],
        detailHeading: "Two moves, structured as one.",
        descArray: [
            "Capital and celebrity, timed to give the round visible runway and fund the campaign that followed.",
            "We led the fundraise for Peep and onboarded Triptii Dimri as the face of the brand in the same window. The ambassador signing was timed to give the round visible runway. The round was sized to fund the campaign that followed.",
            "Peep walked away with the working capital to scale and a brand ambassador whose audience maps cleanly onto the category.",
        ],
        image: "/images/work/brand-peep.png",
        classname: "bg-[#E1DFD2]",
    },
    {
        id: 2,
        title: "KAAI × Tiger Shroff",
        slug: "kaai-tiger-shroff",
        description: "Performance, energy and aspiration, fused into a single signing that gives the brand both scale and depth.",
        engagement: "Strategic Advisory + Brand Ambassador",
        category: "Fashion • Performance",
        scope: "Ongoing advisory",
        services: [
            "Strategy",
            "Talent",
            "brand",
        ],
        detailHeading: "Mass-premium reach, anchored to a strategic seat.",
        descArray: [
            "Performance, energy and aspiration, fused into a single signing that gives the brand both scale and depth.",
            "For KAAI, we serve as strategic advisors and brought Tiger Shroff on as brand ambassador. Tiger’s positioning, performance, energy and mass-premium reach gives KAAI both scale and aspiration in a single signing.",
            "Our advisory mandate covers the broader brand build: how to deploy the ambassador across content, campaigns and channel partnerships so the equity created translates into measurable category share.",
        ],
        image: "/images/work/brand-kaai.png",
        classname: "bg-[#1F3352]",
    },
    {
        id: 3,
        title: "House of Trudys",
        slug: "house-of-trudys",
        description: "A lab-grown diamond brand in the making, built around a strategic anchor for product, retail and narrative.",
        engagement: "Strategic Advisory + Brand Ambassador",
        category: "Fine Jewellery • Lab-Grown Diamonds",
        scope: "Pre-launch advisory",
        services: [
            "Strategy",
            "Talent",
            "brand",
        ],
        detailHeading: "A considered fit, not a stunt signing.",
        descArray: [
            "We're working with The House of Trudys ahead of launch, building a lab-grown diamond brand from the ground up with an ambassador signing at the centre of the engagement. ",
            "The fit is being chosen deliberately. We're matching the brand to a face whose own sense of considered, quiet luxury maps onto where Trudys wants to sit in the market, rather than chasing reach for its own sake.",
            "Beyond the signing itself, we're shaping the brand narrative around the partnership so the ambassador lands as a strategic anchor from day one, carrying through product launches and retail conversations rather than sitting on top of a campaign.",
        ],
        image: "/images/work/brand-trudys.png",
        classname: "bg-[#000000]",
    },
    {
        id: 5,
        title: "Flaunt Your Ink",
        slug: "flaunt-your-ink",
        description: "A venture built from scratch with celebrity co-founders, deploying capital, talent and brand from day one.",
        engagement: "VENTURE BUILD + CELEBRITY CO-FOUNDERS",
        category: "Beauty • Grooming",
        scope: "Active venture build",
        services: [
            "Capital", "talent", "DISTRIBUTION",
            "Strategy",
            "brand",
        ],
        detailHeading: "Built from scratch. Backed from day one.",
        descArray: [
            "Flaunt Your Ink is the engagement where every pillar of our operating system is deployed at once. We led the fundraise, onboarded Suniel Shetty and Haakim Aalim as celebrity co-founders, and built the brand from the ground up: identity, logo, packaging, marketing strategy, the full stack.",
            "The two co-founder structure is deliberate. Suniel brings mass-market trust and decades of affinity with the consumer. Haakim brings cultural credibility and direct access to a tastemaker audience. Together they give the brand both scale and authority from day one.",
        ],
        image: "/images/work/fyi.webp",
        classname: "bg-[#FFFCF0]",
    },
    {
        id: 4,
        title: "Aquatein",
        slug: "",
        description: "",
        engagement: "",
        category: "",
        scope: "",
        services: [
            "Capital",
            "Strategy",
            "brand",
        ],
        detailHeading: "",
        descArray: [
        ],
        image: "/images/work/aquatein.jpg",
        classname: "bg-[#000000]",
    },
    {
        id: 6,
        title: "Excelgenics × NuHer",
        slug: "excelgenics-nuher",
        description: "A dual launch — parent company and hero brand — anchored by a signing that gives the category trust from day one.",
        engagement: "BRAND LAUNCH + BRAND AMBASSADOR",
        category: "Health • Nutraceuticals",
        scope: "Active launch",
        services: [
            "TALENT",
            "Strategy",
            "brand",
        ],
        detailHeading: "A house, and a hero brand.",
        descArray: [
            "Excelgenics is a new nutraceutical company. NuHer is its first hero brand. We are running both launches in lockstep: strategy, digital, marketing, and the full go-to-market for the parent and the lead product. ",
            "To anchor NuHer in a category where trust is everything, we have signed Lisa Ray as the face of the brand. Her credibility in the wellness space gives the partnership a depth that surface-level endorsements cannot manufacture. A launch that lands with weight on day one, not after twelve months of paid spend trying to build it. ",
        ],
        image: "/images/work/excelgenics.avif",
        classname: "bg-[#F5F5F5]",
    },
    {
        id: 7,
        title: "Elyara ",
        slug: "elyara",
        description: "A dermal filler brand built for the prescription pad first — practitioner trust, then patient discovery.",
        engagement: "STRATEGIC ADVISORY",
        category: "Aesthetics • Medical",
        scope: "Ongoing advisory",
        services: [
            "DISTRIBUTION",
            "Strategy",
            "brand",
        ],
        detailHeading: "Built for the prescription pad first.",
        descArray: [
            "Elyara is a dermal filler entering a category where the doctor is the channel and credibility is currency. We are leading the brand build from the ground up: positioning, narrative, and the medical-first story that gives clinicians a reason to recommend it.",
            "The GTM runs in two waves. First, a seeding programme placing Elyara with 50+ doctors who set the bar in aesthetic medicine. Their adoption becomes the proof point for the consumer-facing launch that follows. Practitioner trust first, then patient discovery. Not the other way around. ",
        ],
        image: "/images/work/elyara.png",
        classname: "bg-[#1666BA]",
    },
];